#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from generalpage.ui on Wed Jan 13 22:26:39 2010
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_GeneralPage(object):
    def setupUi(self, GeneralPage):
        GeneralPage.setObjectName("GeneralPage")
        GeneralPage.resize(199, 60)
        self.formLayout = QtGui.QFormLayout(GeneralPage)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(GeneralPage)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.kcfg_serverName = KLineEdit(GeneralPage)
        self.kcfg_serverName.setObjectName("kcfg_serverName")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.kcfg_serverName)
        self.label_2 = QtGui.QLabel(GeneralPage)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.kcfg_portNumber = KIntSpinBox(GeneralPage)
        self.kcfg_portNumber.setMaximum(65536)
        self.kcfg_portNumber.setObjectName("kcfg_portNumber")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.kcfg_portNumber)

        self.retranslateUi(GeneralPage)
        QtCore.QMetaObject.connectSlotsByName(GeneralPage)

    def retranslateUi(self, GeneralPage):
        self.label.setText(kdecore.i18n("Server name:"))
        self.label_2.setText(kdecore.i18n("Port number:"))

from PyKDE4.kdeui import KLineEdit, KIntSpinBox
