print('Home: ' + userDataPath('home'))
print('Desktop: ' + userDataPath('desktop'))
print('Autostart: ' + userDataPath('autostart'))
print('Documents: ' + userDataPath('documents'))
print('Music: ' + userDataPath('music'))
print('Video: ' + userDataPath('video'))
print('Downloads: ' + userDataPath('downloads'))
print('Pictures: ' + userDataPath('pictures'))
print('plasma-desktop data directory: ' + userDataPath('data', 'plasma-desktop'))
print('Okular data directory: ' + userDataPath('data', 'okular'))
print('Okular config: ' + userDataPath('config', 'okularrc'))
print('Icons: ' + userDataPath('icon', ''))
print('Non-existent type: ' + userDataPath('foobar'))

print('Path to Okular: ' + applicationPath('okular'))
print('Path to Okular .desktop file: ' + applicationPath('okular.desktop'))