print("default browser: " + defaultApplication("browser"))
print("default email client: " + defaultApplication("mailer"))
print("default terminal: " + defaultApplication("terminal"))
print("default filemanager (exec): " + defaultApplication("filemanager"))
print("default filemanager (storageId): " + defaultApplication("filemanager", true))
print("default pdf reader (exec): " + defaultApplication("application/pdf"))
print("default pdf reader (storageId): " + defaultApplication("application/pdf", true))
print("default im client: " + defaultApplication("imClient"))
print("should be false: " + defaultApplication("should failure spectacularly"))